// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

package corepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Msg                  []byte   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Data) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type File struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content              []byte        `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	BindKey              string        `protobuf:"bytes,3,opt,name=bind_key,json=bindKey,proto3" json:"bind_key,omitempty"`
	Size                 uint64        `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	State                *StorageState `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{1}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *File) GetBindKey() string {
	if m != nil {
		return m.BindKey
	}
	return ""
}

func (m *File) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetState() *StorageState {
	if m != nil {
		return m.State
	}
	return nil
}

type StorageState struct {
	Mode                 string   `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Result               []byte   `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	ExtraData            []byte   `protobuf:"bytes,3,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageState) Reset()         { *m = StorageState{} }
func (m *StorageState) String() string { return proto.CompactTextString(m) }
func (*StorageState) ProtoMessage()    {}
func (*StorageState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{2}
}

func (m *StorageState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageState.Unmarshal(m, b)
}
func (m *StorageState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageState.Marshal(b, m, deterministic)
}
func (m *StorageState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageState.Merge(m, src)
}
func (m *StorageState) XXX_Size() int {
	return xxx_messageInfo_StorageState.Size(m)
}
func (m *StorageState) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageState.DiscardUnknown(m)
}

var xxx_messageInfo_StorageState proto.InternalMessageInfo

func (m *StorageState) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

func (m *StorageState) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *StorageState) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

type ComplexData struct {
	Flies                []*File  `protobuf:"bytes,1,rep,name=flies,proto3" json:"flies,omitempty"`
	Data                 *Data    `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComplexData) Reset()         { *m = ComplexData{} }
func (m *ComplexData) String() string { return proto.CompactTextString(m) }
func (*ComplexData) ProtoMessage()    {}
func (*ComplexData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{3}
}

func (m *ComplexData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComplexData.Unmarshal(m, b)
}
func (m *ComplexData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComplexData.Marshal(b, m, deterministic)
}
func (m *ComplexData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComplexData.Merge(m, src)
}
func (m *ComplexData) XXX_Size() int {
	return xxx_messageInfo_ComplexData.Size(m)
}
func (m *ComplexData) XXX_DiscardUnknown() {
	xxx_messageInfo_ComplexData.DiscardUnknown(m)
}

var xxx_messageInfo_ComplexData proto.InternalMessageInfo

func (m *ComplexData) GetFlies() []*File {
	if m != nil {
		return m.Flies
	}
	return nil
}

func (m *ComplexData) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type Signature struct {
	Signer               []byte   `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Signature) Reset()         { *m = Signature{} }
func (m *Signature) String() string { return proto.CompactTextString(m) }
func (*Signature) ProtoMessage()    {}
func (*Signature) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{4}
}

func (m *Signature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signature.Unmarshal(m, b)
}
func (m *Signature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signature.Marshal(b, m, deterministic)
}
func (m *Signature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signature.Merge(m, src)
}
func (m *Signature) XXX_Size() int {
	return xxx_messageInfo_Signature.Size(m)
}
func (m *Signature) XXX_DiscardUnknown() {
	xxx_messageInfo_Signature.DiscardUnknown(m)
}

var xxx_messageInfo_Signature proto.InternalMessageInfo

func (m *Signature) GetSigner() []byte {
	if m != nil {
		return m.Signer
	}
	return nil
}

func (m *Signature) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Transaction struct {
	Hash                 []byte     `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	From                 []byte     `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                   []byte     `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value                []byte     `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Nonce                uint64     `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ChainId              uint32     `protobuf:"varint,6,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Fee                  []byte     `protobuf:"bytes,7,opt,name=fee,proto3" json:"fee,omitempty"`
	Timestamp            int64      `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Data                 *Data      `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	Priority             uint32     `protobuf:"varint,10,opt,name=priority,proto3" json:"priority,omitempty"`
	Sign                 *Signature `protobuf:"bytes,11,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{5}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Transaction) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *Transaction) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *Transaction) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *Transaction) GetFee() []byte {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *Transaction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Transaction) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Transaction) GetSign() *Signature {
	if m != nil {
		return m.Sign
	}
	return nil
}

type PsecData struct {
	Term                 int64    `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PsecData) Reset()         { *m = PsecData{} }
func (m *PsecData) String() string { return proto.CompactTextString(m) }
func (*PsecData) ProtoMessage()    {}
func (*PsecData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{6}
}

func (m *PsecData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PsecData.Unmarshal(m, b)
}
func (m *PsecData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PsecData.Marshal(b, m, deterministic)
}
func (m *PsecData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PsecData.Merge(m, src)
}
func (m *PsecData) XXX_Size() int {
	return xxx_messageInfo_PsecData.Size(m)
}
func (m *PsecData) XXX_DiscardUnknown() {
	xxx_messageInfo_PsecData.DiscardUnknown(m)
}

var xxx_messageInfo_PsecData proto.InternalMessageInfo

func (m *PsecData) GetTerm() int64 {
	if m != nil {
		return m.Term
	}
	return 0
}

func (m *PsecData) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type BlockHeader struct {
	Hash                 []byte     `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	ParentHash           []byte     `protobuf:"bytes,2,opt,name=parent_hash,json=parentHash,proto3" json:"parent_hash,omitempty"`
	Coinbase             []byte     `protobuf:"bytes,3,opt,name=coinbase,proto3" json:"coinbase,omitempty"`
	Timestamp            int64      `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ChainId              uint32     `protobuf:"varint,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Height               uint64     `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	TermId               uint64     `protobuf:"varint,7,opt,name=term_id,json=termId,proto3" json:"term_id,omitempty"`
	StateRoot            []byte     `protobuf:"bytes,8,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	TxsRoot              []byte     `protobuf:"bytes,9,opt,name=txs_root,json=txsRoot,proto3" json:"txs_root,omitempty"`
	WitnessRoot          []byte     `protobuf:"bytes,10,opt,name=witness_root,json=witnessRoot,proto3" json:"witness_root,omitempty"`
	Sign                 *Signature `protobuf:"bytes,11,opt,name=sign,proto3" json:"sign,omitempty"`
	Extra                []byte     `protobuf:"bytes,12,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{7}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetParentHash() []byte {
	if m != nil {
		return m.ParentHash
	}
	return nil
}

func (m *BlockHeader) GetCoinbase() []byte {
	if m != nil {
		return m.Coinbase
	}
	return nil
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *BlockHeader) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockHeader) GetTermId() uint64 {
	if m != nil {
		return m.TermId
	}
	return 0
}

func (m *BlockHeader) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *BlockHeader) GetTxsRoot() []byte {
	if m != nil {
		return m.TxsRoot
	}
	return nil
}

func (m *BlockHeader) GetWitnessRoot() []byte {
	if m != nil {
		return m.WitnessRoot
	}
	return nil
}

func (m *BlockHeader) GetSign() *Signature {
	if m != nil {
		return m.Sign
	}
	return nil
}

func (m *BlockHeader) GetExtra() []byte {
	if m != nil {
		return m.Extra
	}
	return nil
}

type Block struct {
	Hash                 []byte         `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Header               *BlockHeader   `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Body                 []*Transaction `protobuf:"bytes,3,rep,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{8}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetBody() []*Transaction {
	if m != nil {
		return m.Body
	}
	return nil
}

type DownloadBlock struct {
	Hash                 []byte     `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Sign                 *Signature `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DownloadBlock) Reset()         { *m = DownloadBlock{} }
func (m *DownloadBlock) String() string { return proto.CompactTextString(m) }
func (*DownloadBlock) ProtoMessage()    {}
func (*DownloadBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{9}
}

func (m *DownloadBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadBlock.Unmarshal(m, b)
}
func (m *DownloadBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadBlock.Marshal(b, m, deterministic)
}
func (m *DownloadBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadBlock.Merge(m, src)
}
func (m *DownloadBlock) XXX_Size() int {
	return xxx_messageInfo_DownloadBlock.Size(m)
}
func (m *DownloadBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadBlock.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadBlock proto.InternalMessageInfo

func (m *DownloadBlock) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *DownloadBlock) GetSign() *Signature {
	if m != nil {
		return m.Sign
	}
	return nil
}

type Promise struct {
	ProposalId           uint64   `protobuf:"varint,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	MaxAcceptedPropose   *Propose `protobuf:"bytes,2,opt,name=max_accepted_propose,json=maxAcceptedPropose,proto3" json:"max_accepted_propose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Promise) Reset()         { *m = Promise{} }
func (m *Promise) String() string { return proto.CompactTextString(m) }
func (*Promise) ProtoMessage()    {}
func (*Promise) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{10}
}

func (m *Promise) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Promise.Unmarshal(m, b)
}
func (m *Promise) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Promise.Marshal(b, m, deterministic)
}
func (m *Promise) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Promise.Merge(m, src)
}
func (m *Promise) XXX_Size() int {
	return xxx_messageInfo_Promise.Size(m)
}
func (m *Promise) XXX_DiscardUnknown() {
	xxx_messageInfo_Promise.DiscardUnknown(m)
}

var xxx_messageInfo_Promise proto.InternalMessageInfo

func (m *Promise) GetProposalId() uint64 {
	if m != nil {
		return m.ProposalId
	}
	return 0
}

func (m *Promise) GetMaxAcceptedPropose() *Propose {
	if m != nil {
		return m.MaxAcceptedPropose
	}
	return nil
}

type Propose struct {
	Num                  uint64     `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	Value                []byte     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Sign                 *Signature `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Propose) Reset()         { *m = Propose{} }
func (m *Propose) String() string { return proto.CompactTextString(m) }
func (*Propose) ProtoMessage()    {}
func (*Propose) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{11}
}

func (m *Propose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Propose.Unmarshal(m, b)
}
func (m *Propose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Propose.Marshal(b, m, deterministic)
}
func (m *Propose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Propose.Merge(m, src)
}
func (m *Propose) XXX_Size() int {
	return xxx_messageInfo_Propose.Size(m)
}
func (m *Propose) XXX_DiscardUnknown() {
	xxx_messageInfo_Propose.DiscardUnknown(m)
}

var xxx_messageInfo_Propose proto.InternalMessageInfo

func (m *Propose) GetNum() uint64 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *Propose) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Propose) GetSign() *Signature {
	if m != nil {
		return m.Sign
	}
	return nil
}

type PreprepareMsg struct {
	Timestamp            int64      `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Type                 uint32     `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	ViewId               string     `protobuf:"bytes,3,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	SeqId                uint64     `protobuf:"varint,4,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Hash                 []byte     `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	Block                *Block     `protobuf:"bytes,6,opt,name=block,proto3" json:"block,omitempty"`
	Sign                 *Signature `protobuf:"bytes,7,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PreprepareMsg) Reset()         { *m = PreprepareMsg{} }
func (m *PreprepareMsg) String() string { return proto.CompactTextString(m) }
func (*PreprepareMsg) ProtoMessage()    {}
func (*PreprepareMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{12}
}

func (m *PreprepareMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PreprepareMsg.Unmarshal(m, b)
}
func (m *PreprepareMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PreprepareMsg.Marshal(b, m, deterministic)
}
func (m *PreprepareMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PreprepareMsg.Merge(m, src)
}
func (m *PreprepareMsg) XXX_Size() int {
	return xxx_messageInfo_PreprepareMsg.Size(m)
}
func (m *PreprepareMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PreprepareMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PreprepareMsg proto.InternalMessageInfo

func (m *PreprepareMsg) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PreprepareMsg) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *PreprepareMsg) GetViewId() string {
	if m != nil {
		return m.ViewId
	}
	return ""
}

func (m *PreprepareMsg) GetSeqId() uint64 {
	if m != nil {
		return m.SeqId
	}
	return 0
}

func (m *PreprepareMsg) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *PreprepareMsg) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *PreprepareMsg) GetSign() *Signature {
	if m != nil {
		return m.Sign
	}
	return nil
}

type VoteMsg struct {
	Type                 uint32     `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	ViewId               string     `protobuf:"bytes,2,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	SeqId                uint64     `protobuf:"varint,3,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Hash                 []byte     `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	Sign                 *Signature `protobuf:"bytes,5,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *VoteMsg) Reset()         { *m = VoteMsg{} }
func (m *VoteMsg) String() string { return proto.CompactTextString(m) }
func (*VoteMsg) ProtoMessage()    {}
func (*VoteMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e550b1f5926e92d, []int{13}
}

func (m *VoteMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteMsg.Unmarshal(m, b)
}
func (m *VoteMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteMsg.Marshal(b, m, deterministic)
}
func (m *VoteMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteMsg.Merge(m, src)
}
func (m *VoteMsg) XXX_Size() int {
	return xxx_messageInfo_VoteMsg.Size(m)
}
func (m *VoteMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteMsg.DiscardUnknown(m)
}

var xxx_messageInfo_VoteMsg proto.InternalMessageInfo

func (m *VoteMsg) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *VoteMsg) GetViewId() string {
	if m != nil {
		return m.ViewId
	}
	return ""
}

func (m *VoteMsg) GetSeqId() uint64 {
	if m != nil {
		return m.SeqId
	}
	return 0
}

func (m *VoteMsg) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *VoteMsg) GetSign() *Signature {
	if m != nil {
		return m.Sign
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "corepb.Data")
	proto.RegisterType((*File)(nil), "corepb.File")
	proto.RegisterType((*StorageState)(nil), "corepb.StorageState")
	proto.RegisterType((*ComplexData)(nil), "corepb.ComplexData")
	proto.RegisterType((*Signature)(nil), "corepb.Signature")
	proto.RegisterType((*Transaction)(nil), "corepb.Transaction")
	proto.RegisterType((*PsecData)(nil), "corepb.PsecData")
	proto.RegisterType((*BlockHeader)(nil), "corepb.BlockHeader")
	proto.RegisterType((*Block)(nil), "corepb.Block")
	proto.RegisterType((*DownloadBlock)(nil), "corepb.DownloadBlock")
	proto.RegisterType((*Promise)(nil), "corepb.Promise")
	proto.RegisterType((*Propose)(nil), "corepb.Propose")
	proto.RegisterType((*PreprepareMsg)(nil), "corepb.PreprepareMsg")
	proto.RegisterType((*VoteMsg)(nil), "corepb.VoteMsg")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor_8e550b1f5926e92d) }

var fileDescriptor_8e550b1f5926e92d = []byte{
	// 853 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcd, 0x6e, 0xe4, 0x44,
	0x10, 0x96, 0x3d, 0xf6, 0x78, 0xa6, 0xec, 0xf0, 0xd3, 0x84, 0x5d, 0xb3, 0x02, 0x31, 0x18, 0x21,
	0x46, 0x80, 0x72, 0x08, 0x07, 0x2e, 0x5c, 0x16, 0x56, 0x68, 0x07, 0x84, 0x14, 0x75, 0x10, 0x82,
	0xd3, 0xa8, 0xc7, 0xae, 0xcc, 0x58, 0x3b, 0x76, 0x3b, 0xee, 0xce, 0x66, 0xc2, 0x13, 0x70, 0xe3,
	0x19, 0x78, 0x24, 0x5e, 0x81, 0x27, 0x41, 0x55, 0x6d, 0x3b, 0x33, 0x21, 0x89, 0xf6, 0x56, 0xbf,
	0xdd, 0x55, 0x5f, 0x7d, 0xd5, 0x0d, 0xf1, 0x6a, 0xab, 0xf3, 0x57, 0x27, 0x4d, 0xab, 0xad, 0x16,
	0xe3, 0x5c, 0xb7, 0xd8, 0xac, 0xb2, 0xaf, 0x20, 0x78, 0xa1, 0xac, 0x12, 0x02, 0x02, 0x7b, 0xd3,
	0x60, 0xea, 0xcd, 0xbc, 0xf9, 0x54, 0xb2, 0x2c, 0xde, 0x81, 0x51, 0x65, 0xd6, 0xa9, 0x3f, 0xf3,
	0xe6, 0x89, 0x24, 0x31, 0xfb, 0xcb, 0x83, 0xe0, 0x87, 0x72, 0x8b, 0x14, 0x5e, 0xab, 0x6a, 0x08,
	0x27, 0x59, 0xa4, 0x10, 0xe5, 0xba, 0xb6, 0x58, 0xdb, 0x2e, 0xa5, 0x57, 0xc5, 0x07, 0x30, 0x59,
	0x95, 0x75, 0xb1, 0x7c, 0x85, 0x37, 0xe9, 0x88, 0x33, 0x22, 0xd2, 0x7f, 0xc2, 0x1b, 0x3a, 0xc8,
	0x94, 0x7f, 0x60, 0x1a, 0xcc, 0xbc, 0x79, 0x20, 0x59, 0x16, 0x5f, 0x40, 0x68, 0xac, 0xb2, 0x98,
	0x86, 0x33, 0x6f, 0x1e, 0x9f, 0x1e, 0x9f, 0xb8, 0x5a, 0x4f, 0xce, 0xad, 0x6e, 0xd5, 0x1a, 0xcf,
	0xc9, 0x27, 0x5d, 0x48, 0xf6, 0x3b, 0x24, 0xfb, 0x66, 0x3a, 0xaf, 0xd2, 0xc5, 0x50, 0x18, 0xc9,
	0xe2, 0x09, 0x8c, 0x5b, 0x34, 0x57, 0xdb, 0xbe, 0xae, 0x4e, 0x13, 0x1f, 0x01, 0xe0, 0xce, 0xb6,
	0x6a, 0x59, 0x28, 0xab, 0xb8, 0xb0, 0x44, 0x4e, 0xd9, 0x42, 0x90, 0x64, 0xe7, 0x10, 0x7f, 0xaf,
	0xab, 0x66, 0x8b, 0x3b, 0x46, 0x28, 0x83, 0xf0, 0x62, 0x5b, 0xa2, 0x49, 0xbd, 0xd9, 0x68, 0x1e,
	0x9f, 0x26, 0x7d, 0x55, 0x84, 0x87, 0x74, 0x2e, 0x31, 0x83, 0x80, 0xcf, 0xf2, 0xb9, 0xf0, 0x21,
	0x84, 0xf2, 0x25, 0x7b, 0xb2, 0x6f, 0x60, 0x7a, 0x5e, 0xae, 0x6b, 0x65, 0xaf, 0x5a, 0x2e, 0xcc,
	0x94, 0xeb, 0x1a, 0x5b, 0x2e, 0x37, 0x91, 0x9d, 0x46, 0x4d, 0x0c, 0xc7, 0x24, 0x5d, 0xe2, 0xdf,
	0x3e, 0xc4, 0xbf, 0xb4, 0xaa, 0x36, 0x2a, 0xb7, 0xa5, 0xae, 0x29, 0x66, 0xa3, 0xcc, 0xa6, 0xcb,
	0x64, 0x99, 0x6c, 0x17, 0xad, 0xae, 0xfa, 0x3c, 0x92, 0xc5, 0x5b, 0xe0, 0x5b, 0xdd, 0x35, 0xe7,
	0x5b, 0x2d, 0x8e, 0x21, 0x7c, 0xad, 0xb6, 0x57, 0x0e, 0xf1, 0x44, 0x3a, 0x85, 0xac, 0xb5, 0xae,
	0x73, 0x07, 0x79, 0x20, 0x9d, 0x42, 0x73, 0xcb, 0x37, 0xaa, 0xac, 0x97, 0x65, 0x91, 0x8e, 0x67,
	0xde, 0xfc, 0x48, 0x46, 0xac, 0x2f, 0x0a, 0xe2, 0xc6, 0x05, 0x62, 0x1a, 0x39, 0x6e, 0x5c, 0x20,
	0x8a, 0x0f, 0x61, 0x6a, 0xcb, 0x0a, 0x8d, 0x55, 0x55, 0x93, 0x4e, 0x66, 0xde, 0x7c, 0x24, 0x6f,
	0x0d, 0x03, 0x32, 0xd3, 0x87, 0x90, 0x11, 0xcf, 0x60, 0xd2, 0xb4, 0xa5, 0x6e, 0x4b, 0x7b, 0x93,
	0x02, 0x5f, 0x36, 0xe8, 0xe2, 0x33, 0x62, 0xc9, 0xba, 0x4e, 0x63, 0xce, 0x7e, 0x77, 0x20, 0x44,
	0x8f, 0xa4, 0x64, 0x77, 0xf6, 0x2d, 0x4c, 0xce, 0x0c, 0xe6, 0x03, 0xa1, 0xb1, 0xad, 0x18, 0x9f,
	0x91, 0x64, 0xf9, 0xb0, 0x44, 0xff, 0x4e, 0x89, 0xd9, 0xbf, 0x3e, 0xc4, 0xdf, 0xd1, 0x8a, 0xbc,
	0x44, 0x55, 0xb8, 0x29, 0xfc, 0x0f, 0xe1, 0x8f, 0x21, 0x6e, 0x54, 0x8b, 0xb5, 0x5d, 0xb2, 0xcb,
	0x01, 0x0d, 0xce, 0xf4, 0x92, 0x02, 0x9e, 0xc1, 0x24, 0xd7, 0x65, 0xbd, 0x52, 0x06, 0x3b, 0xd0,
	0x07, 0xfd, 0xf0, 0xfa, 0xe0, 0x2e, 0x42, 0xfb, 0x60, 0x87, 0x87, 0x60, 0x3f, 0x81, 0xf1, 0x06,
	0xcb, 0xf5, 0xc6, 0xf2, 0x14, 0x02, 0xd9, 0x69, 0xe2, 0x29, 0x44, 0xd4, 0x17, 0x65, 0x44, 0xce,
	0x41, 0xea, 0xa2, 0x20, 0x66, 0xf3, 0x7a, 0x2c, 0x5b, 0xad, 0x2d, 0x0f, 0x23, 0x91, 0x53, 0xb6,
	0x48, 0xad, 0x79, 0x1f, 0xed, 0xce, 0x38, 0xe7, 0xd4, 0xad, 0xaa, 0xdd, 0x19, 0x76, 0x7d, 0x02,
	0xc9, 0x75, 0x69, 0x6b, 0x34, 0x9d, 0x1b, 0xd8, 0x1d, 0x77, 0x36, 0x0e, 0x79, 0xb3, 0x61, 0x10,
	0xa5, 0x78, 0x97, 0xd2, 0xc4, 0x11, 0x8d, 0x95, 0xec, 0x12, 0x42, 0xc6, 0xf8, 0x5e, 0x74, 0xbf,
	0xa4, 0x3e, 0x09, 0xfb, 0x6e, 0x81, 0xde, 0xeb, 0xcf, 0xde, 0x1b, 0x8b, 0xec, 0x42, 0xc4, 0xe7,
	0x10, 0xac, 0x74, 0x41, 0x0f, 0xca, 0x68, 0x3f, 0x74, 0x6f, 0x47, 0x24, 0x07, 0x64, 0x3f, 0xc2,
	0xd1, 0x0b, 0x7d, 0x5d, 0x6f, 0xb5, 0x2a, 0x1e, 0xbe, 0xba, 0x6f, 0xca, 0x7f, 0x9c, 0x61, 0x15,
	0x44, 0x67, 0xad, 0xae, 0x4a, 0x83, 0x4c, 0x85, 0x56, 0x37, 0xda, 0xa8, 0x2d, 0x0d, 0xc0, 0xe3,
	0x01, 0x40, 0x6f, 0x5a, 0x14, 0xe2, 0x39, 0x1c, 0x57, 0x6a, 0xb7, 0x54, 0x79, 0x8e, 0x8d, 0xc5,
	0x62, 0xe9, 0x5c, 0xd8, 0x5d, 0xf1, 0x76, 0x7f, 0xc5, 0x99, 0x33, 0x4b, 0x51, 0xa9, 0xdd, 0xf3,
	0x2e, 0xb6, 0xb3, 0x65, 0xbf, 0xf1, 0x75, 0x24, 0xd2, 0xc2, 0xd5, 0x57, 0x55, 0x77, 0x0d, 0x89,
	0xb7, 0x9b, 0xec, 0xef, 0x6f, 0x72, 0xdf, 0xc8, 0xe8, 0xf1, 0x46, 0xfe, 0xf1, 0xe0, 0xe8, 0xac,
	0xc5, 0xa6, 0x45, 0x22, 0xef, 0xcf, 0x66, 0x7d, 0xc8, 0x4e, 0xef, 0x2e, 0x3b, 0xfb, 0xff, 0xc1,
	0x67, 0x66, 0xba, 0xff, 0xe1, 0x29, 0x44, 0xaf, 0x4b, 0xbc, 0xa6, 0xee, 0xdd, 0xab, 0x3e, 0x26,
	0x75, 0x51, 0x88, 0xf7, 0x61, 0x6c, 0xf0, 0x92, 0xec, 0xee, 0x59, 0x0f, 0x0d, 0x5e, 0x2e, 0x8a,
	0x01, 0xf7, 0x70, 0x0f, 0xf7, 0x4f, 0x21, 0xe4, 0x6f, 0x89, 0x99, 0x1d, 0x9f, 0x1e, 0x1d, 0x4c,
	0x5c, 0x3a, 0xdf, 0xd0, 0x53, 0xf4, 0x78, 0x4f, 0x7f, 0x7a, 0x10, 0xfd, 0xaa, 0x2d, 0x77, 0xb3,
	0xff, 0x9f, 0xdd, 0x53, 0xaf, 0xff, 0x40, 0xbd, 0xa3, 0xfb, 0xea, 0x0d, 0xee, 0xe1, 0x49, 0xf8,
	0x68, 0x29, 0xab, 0x31, 0xff, 0xb2, 0x5f, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x96, 0xc6, 0xe1,
	0x6a, 0x74, 0x07, 0x00, 0x00,
}
