// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpcpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request message of non params.
type NonParamsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NonParamsRequest) Reset()         { *m = NonParamsRequest{} }
func (m *NonParamsRequest) String() string { return proto.CompactTextString(m) }
func (*NonParamsRequest) ProtoMessage()    {}
func (*NonParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *NonParamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NonParamsRequest.Unmarshal(m, b)
}
func (m *NonParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NonParamsRequest.Marshal(b, m, deterministic)
}
func (m *NonParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NonParamsRequest.Merge(m, src)
}
func (m *NonParamsRequest) XXX_Size() int {
	return xxx_messageInfo_NonParamsRequest.Size(m)
}
func (m *NonParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NonParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NonParamsRequest proto.InternalMessageInfo

// Response message of Accounts rpc.
type AccountsResponse struct {
	// Account list
	Addresses            []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountsResponse) Reset()         { *m = AccountsResponse{} }
func (m *AccountsResponse) String() string { return proto.CompactTextString(m) }
func (*AccountsResponse) ProtoMessage()    {}
func (*AccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *AccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountsResponse.Unmarshal(m, b)
}
func (m *AccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountsResponse.Marshal(b, m, deterministic)
}
func (m *AccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountsResponse.Merge(m, src)
}
func (m *AccountsResponse) XXX_Size() int {
	return xxx_messageInfo_AccountsResponse.Size(m)
}
func (m *AccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountsResponse proto.InternalMessageInfo

func (m *AccountsResponse) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type PassphraseRequest struct {
	Passphrase           string   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PassphraseRequest) Reset()         { *m = PassphraseRequest{} }
func (m *PassphraseRequest) String() string { return proto.CompactTextString(m) }
func (*PassphraseRequest) ProtoMessage()    {}
func (*PassphraseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *PassphraseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PassphraseRequest.Unmarshal(m, b)
}
func (m *PassphraseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PassphraseRequest.Marshal(b, m, deterministic)
}
func (m *PassphraseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PassphraseRequest.Merge(m, src)
}
func (m *PassphraseRequest) XXX_Size() int {
	return xxx_messageInfo_PassphraseRequest.Size(m)
}
func (m *PassphraseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PassphraseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PassphraseRequest proto.InternalMessageInfo

func (m *PassphraseRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type UpdateAccountRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	OldPassphrase        string   `protobuf:"bytes,2,opt,name=old_passphrase,json=oldPassphrase,proto3" json:"old_passphrase,omitempty"`
	NewPassphrase        string   `protobuf:"bytes,3,opt,name=new_passphrase,json=newPassphrase,proto3" json:"new_passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(m, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UpdateAccountRequest) GetOldPassphrase() string {
	if m != nil {
		return m.OldPassphrase
	}
	return ""
}

func (m *UpdateAccountRequest) GetNewPassphrase() string {
	if m != nil {
		return m.NewPassphrase
	}
	return ""
}

type NewAccountResponse struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Memo                 string   `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewAccountResponse) Reset()         { *m = NewAccountResponse{} }
func (m *NewAccountResponse) String() string { return proto.CompactTextString(m) }
func (*NewAccountResponse) ProtoMessage()    {}
func (*NewAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *NewAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewAccountResponse.Unmarshal(m, b)
}
func (m *NewAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewAccountResponse.Marshal(b, m, deterministic)
}
func (m *NewAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewAccountResponse.Merge(m, src)
}
func (m *NewAccountResponse) XXX_Size() int {
	return xxx_messageInfo_NewAccountResponse.Size(m)
}
func (m *NewAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NewAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NewAccountResponse proto.InternalMessageInfo

func (m *NewAccountResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NewAccountResponse) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

type UnlockAccountRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Passphrase           string   `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	Duration             uint64   `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlockAccountRequest) Reset()         { *m = UnlockAccountRequest{} }
func (m *UnlockAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UnlockAccountRequest) ProtoMessage()    {}
func (*UnlockAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *UnlockAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlockAccountRequest.Unmarshal(m, b)
}
func (m *UnlockAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlockAccountRequest.Marshal(b, m, deterministic)
}
func (m *UnlockAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlockAccountRequest.Merge(m, src)
}
func (m *UnlockAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UnlockAccountRequest.Size(m)
}
func (m *UnlockAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlockAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlockAccountRequest proto.InternalMessageInfo

func (m *UnlockAccountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UnlockAccountRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

func (m *UnlockAccountRequest) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type LockAccountRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LockAccountRequest) Reset()         { *m = LockAccountRequest{} }
func (m *LockAccountRequest) String() string { return proto.CompactTextString(m) }
func (*LockAccountRequest) ProtoMessage()    {}
func (*LockAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *LockAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LockAccountRequest.Unmarshal(m, b)
}
func (m *LockAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LockAccountRequest.Marshal(b, m, deterministic)
}
func (m *LockAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockAccountRequest.Merge(m, src)
}
func (m *LockAccountRequest) XXX_Size() int {
	return xxx_messageInfo_LockAccountRequest.Size(m)
}
func (m *LockAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LockAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LockAccountRequest proto.InternalMessageInfo

func (m *LockAccountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type SignHashRequest struct {
	// sign address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	//hex string of hash
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// sign algorithm
	Alg                  uint32   `protobuf:"varint,3,opt,name=alg,proto3" json:"alg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignHashRequest) Reset()         { *m = SignHashRequest{} }
func (m *SignHashRequest) String() string { return proto.CompactTextString(m) }
func (*SignHashRequest) ProtoMessage()    {}
func (*SignHashRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *SignHashRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignHashRequest.Unmarshal(m, b)
}
func (m *SignHashRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignHashRequest.Marshal(b, m, deterministic)
}
func (m *SignHashRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignHashRequest.Merge(m, src)
}
func (m *SignHashRequest) XXX_Size() int {
	return xxx_messageInfo_SignHashRequest.Size(m)
}
func (m *SignHashRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignHashRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignHashRequest proto.InternalMessageInfo

func (m *SignHashRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SignHashRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SignHashRequest) GetAlg() uint32 {
	if m != nil {
		return m.Alg
	}
	return 0
}

type VerifyMessageRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	//hex string of signature
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	//hex string of sign msg
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyMessageRequest) Reset()         { *m = VerifyMessageRequest{} }
func (m *VerifyMessageRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyMessageRequest) ProtoMessage()    {}
func (*VerifyMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *VerifyMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyMessageRequest.Unmarshal(m, b)
}
func (m *VerifyMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyMessageRequest.Marshal(b, m, deterministic)
}
func (m *VerifyMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyMessageRequest.Merge(m, src)
}
func (m *VerifyMessageRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyMessageRequest.Size(m)
}
func (m *VerifyMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyMessageRequest proto.InternalMessageInfo

func (m *VerifyMessageRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *VerifyMessageRequest) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *VerifyMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SignHashResponse struct {
	//hex string of the data
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignHashResponse) Reset()         { *m = SignHashResponse{} }
func (m *SignHashResponse) String() string { return proto.CompactTextString(m) }
func (*SignHashResponse) ProtoMessage()    {}
func (*SignHashResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *SignHashResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignHashResponse.Unmarshal(m, b)
}
func (m *SignHashResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignHashResponse.Marshal(b, m, deterministic)
}
func (m *SignHashResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignHashResponse.Merge(m, src)
}
func (m *SignHashResponse) XXX_Size() int {
	return xxx_messageInfo_SignHashResponse.Size(m)
}
func (m *SignHashResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignHashResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignHashResponse proto.InternalMessageInfo

func (m *SignHashResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SignTransactionPassphraseRequest struct {
	// transaction struct
	Transaction *TransactionRequest `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// from account passphrase
	Passphrase           string   `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignTransactionPassphraseRequest) Reset()         { *m = SignTransactionPassphraseRequest{} }
func (m *SignTransactionPassphraseRequest) String() string { return proto.CompactTextString(m) }
func (*SignTransactionPassphraseRequest) ProtoMessage()    {}
func (*SignTransactionPassphraseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *SignTransactionPassphraseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTransactionPassphraseRequest.Unmarshal(m, b)
}
func (m *SignTransactionPassphraseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTransactionPassphraseRequest.Marshal(b, m, deterministic)
}
func (m *SignTransactionPassphraseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTransactionPassphraseRequest.Merge(m, src)
}
func (m *SignTransactionPassphraseRequest) XXX_Size() int {
	return xxx_messageInfo_SignTransactionPassphraseRequest.Size(m)
}
func (m *SignTransactionPassphraseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTransactionPassphraseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignTransactionPassphraseRequest proto.InternalMessageInfo

func (m *SignTransactionPassphraseRequest) GetTransaction() *TransactionRequest {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *SignTransactionPassphraseRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type SignTransactionPassphraseResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignTransactionPassphraseResponse) Reset()         { *m = SignTransactionPassphraseResponse{} }
func (m *SignTransactionPassphraseResponse) String() string { return proto.CompactTextString(m) }
func (*SignTransactionPassphraseResponse) ProtoMessage()    {}
func (*SignTransactionPassphraseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *SignTransactionPassphraseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignTransactionPassphraseResponse.Unmarshal(m, b)
}
func (m *SignTransactionPassphraseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignTransactionPassphraseResponse.Marshal(b, m, deterministic)
}
func (m *SignTransactionPassphraseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignTransactionPassphraseResponse.Merge(m, src)
}
func (m *SignTransactionPassphraseResponse) XXX_Size() int {
	return xxx_messageInfo_SignTransactionPassphraseResponse.Size(m)
}
func (m *SignTransactionPassphraseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignTransactionPassphraseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignTransactionPassphraseResponse proto.InternalMessageInfo

func (m *SignTransactionPassphraseResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SendTransactionPassphraseRequest struct {
	// transaction struct
	Transaction *TransactionRequest `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// from account passphrase
	Passphrase           string   `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTransactionPassphraseRequest) Reset()         { *m = SendTransactionPassphraseRequest{} }
func (m *SendTransactionPassphraseRequest) String() string { return proto.CompactTextString(m) }
func (*SendTransactionPassphraseRequest) ProtoMessage()    {}
func (*SendTransactionPassphraseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12}
}

func (m *SendTransactionPassphraseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTransactionPassphraseRequest.Unmarshal(m, b)
}
func (m *SendTransactionPassphraseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTransactionPassphraseRequest.Marshal(b, m, deterministic)
}
func (m *SendTransactionPassphraseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTransactionPassphraseRequest.Merge(m, src)
}
func (m *SendTransactionPassphraseRequest) XXX_Size() int {
	return xxx_messageInfo_SendTransactionPassphraseRequest.Size(m)
}
func (m *SendTransactionPassphraseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTransactionPassphraseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendTransactionPassphraseRequest proto.InternalMessageInfo

func (m *SendTransactionPassphraseRequest) GetTransaction() *TransactionRequest {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *SendTransactionPassphraseRequest) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

type GasPriceResponse struct {
	GasPrice             string   `protobuf:"bytes,1,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GasPriceResponse) Reset()         { *m = GasPriceResponse{} }
func (m *GasPriceResponse) String() string { return proto.CompactTextString(m) }
func (*GasPriceResponse) ProtoMessage()    {}
func (*GasPriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{13}
}

func (m *GasPriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GasPriceResponse.Unmarshal(m, b)
}
func (m *GasPriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GasPriceResponse.Marshal(b, m, deterministic)
}
func (m *GasPriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GasPriceResponse.Merge(m, src)
}
func (m *GasPriceResponse) XXX_Size() int {
	return xxx_messageInfo_GasPriceResponse.Size(m)
}
func (m *GasPriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GasPriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GasPriceResponse proto.InternalMessageInfo

func (m *GasPriceResponse) GetGasPrice() string {
	if m != nil {
		return m.GasPrice
	}
	return ""
}

type PprofRequest struct {
	Listen               string   `protobuf:"bytes,1,opt,name=listen,proto3" json:"listen,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PprofRequest) Reset()         { *m = PprofRequest{} }
func (m *PprofRequest) String() string { return proto.CompactTextString(m) }
func (*PprofRequest) ProtoMessage()    {}
func (*PprofRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{14}
}

func (m *PprofRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PprofRequest.Unmarshal(m, b)
}
func (m *PprofRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PprofRequest.Marshal(b, m, deterministic)
}
func (m *PprofRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PprofRequest.Merge(m, src)
}
func (m *PprofRequest) XXX_Size() int {
	return xxx_messageInfo_PprofRequest.Size(m)
}
func (m *PprofRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PprofRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PprofRequest proto.InternalMessageInfo

func (m *PprofRequest) GetListen() string {
	if m != nil {
		return m.Listen
	}
	return ""
}

type PprofResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PprofResponse) Reset()         { *m = PprofResponse{} }
func (m *PprofResponse) String() string { return proto.CompactTextString(m) }
func (*PprofResponse) ProtoMessage()    {}
func (*PprofResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{15}
}

func (m *PprofResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PprofResponse.Unmarshal(m, b)
}
func (m *PprofResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PprofResponse.Marshal(b, m, deterministic)
}
func (m *PprofResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PprofResponse.Merge(m, src)
}
func (m *PprofResponse) XXX_Size() int {
	return xxx_messageInfo_PprofResponse.Size(m)
}
func (m *PprofResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PprofResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PprofResponse proto.InternalMessageInfo

func (m *PprofResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type TransactionHash struct {
	// Hex string of transaction hash.
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionHash) Reset()         { *m = TransactionHash{} }
func (m *TransactionHash) String() string { return proto.CompactTextString(m) }
func (*TransactionHash) ProtoMessage()    {}
func (*TransactionHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{16}
}

func (m *TransactionHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionHash.Unmarshal(m, b)
}
func (m *TransactionHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionHash.Marshal(b, m, deterministic)
}
func (m *TransactionHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionHash.Merge(m, src)
}
func (m *TransactionHash) XXX_Size() int {
	return xxx_messageInfo_TransactionHash.Size(m)
}
func (m *TransactionHash) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionHash.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionHash proto.InternalMessageInfo

func (m *TransactionHash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// Request message of SendTransaction rpc.
type TransactionRequest struct {
	// Hex string of the sender account addresss.
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// Hex string of the receiver account addresss.
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Amount of value sending with this transaction.
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	// Transaction nonce.
	Nonce uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// binary data for transaction
	//hex encode
	Data string `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	// transaction payload type, enum:binary, deploy, call, protocol
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Priority             uint32   `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{17}
}

func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (m *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(m, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

func (m *TransactionRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *TransactionRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *TransactionRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TransactionRequest) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TransactionRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *TransactionRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TransactionRequest) GetPriority() uint32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

type BoolResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolResponse) Reset()         { *m = BoolResponse{} }
func (m *BoolResponse) String() string { return proto.CompactTextString(m) }
func (*BoolResponse) ProtoMessage()    {}
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{18}
}

func (m *BoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolResponse.Unmarshal(m, b)
}
func (m *BoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolResponse.Marshal(b, m, deterministic)
}
func (m *BoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolResponse.Merge(m, src)
}
func (m *BoolResponse) XXX_Size() int {
	return xxx_messageInfo_BoolResponse.Size(m)
}
func (m *BoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BoolResponse proto.InternalMessageInfo

func (m *BoolResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

type Address struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{19}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type BalanceResponse struct {
	Balance              string   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	FrozenFund           string   `protobuf:"bytes,2,opt,name=frozen_fund,json=frozenFund,proto3" json:"frozen_fund,omitempty"`
	PledgeFund           string   `protobuf:"bytes,3,opt,name=pledge_fund,json=pledgeFund,proto3" json:"pledge_fund,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceResponse) Reset()         { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()    {}
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{20}
}

func (m *BalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResponse.Unmarshal(m, b)
}
func (m *BalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResponse.Marshal(b, m, deterministic)
}
func (m *BalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResponse.Merge(m, src)
}
func (m *BalanceResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceResponse.Size(m)
}
func (m *BalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResponse proto.InternalMessageInfo

func (m *BalanceResponse) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *BalanceResponse) GetFrozenFund() string {
	if m != nil {
		return m.FrozenFund
	}
	return ""
}

func (m *BalanceResponse) GetPledgeFund() string {
	if m != nil {
		return m.PledgeFund
	}
	return ""
}

type LoggingInfo struct {
	LogLevel             string   `protobuf:"bytes,1,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	LogPath              string   `protobuf:"bytes,2,opt,name=log_path,json=logPath,proto3" json:"log_path,omitempty"`
	RotationTime         uint32   `protobuf:"varint,3,opt,name=rotation_time,json=rotationTime,proto3" json:"rotation_time,omitempty"`
	LogAge               uint32   `protobuf:"varint,4,opt,name=log_age,json=logAge,proto3" json:"log_age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoggingInfo) Reset()         { *m = LoggingInfo{} }
func (m *LoggingInfo) String() string { return proto.CompactTextString(m) }
func (*LoggingInfo) ProtoMessage()    {}
func (*LoggingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{21}
}

func (m *LoggingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoggingInfo.Unmarshal(m, b)
}
func (m *LoggingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoggingInfo.Marshal(b, m, deterministic)
}
func (m *LoggingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoggingInfo.Merge(m, src)
}
func (m *LoggingInfo) XXX_Size() int {
	return xxx_messageInfo_LoggingInfo.Size(m)
}
func (m *LoggingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LoggingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LoggingInfo proto.InternalMessageInfo

func (m *LoggingInfo) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

func (m *LoggingInfo) GetLogPath() string {
	if m != nil {
		return m.LogPath
	}
	return ""
}

func (m *LoggingInfo) GetRotationTime() uint32 {
	if m != nil {
		return m.RotationTime
	}
	return 0
}

func (m *LoggingInfo) GetLogAge() uint32 {
	if m != nil {
		return m.LogAge
	}
	return 0
}

type PrivateKey struct {
	PriKey               string   `protobuf:"bytes,1,opt,name=pri_key,json=priKey,proto3" json:"pri_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivateKey) Reset()         { *m = PrivateKey{} }
func (m *PrivateKey) String() string { return proto.CompactTextString(m) }
func (*PrivateKey) ProtoMessage()    {}
func (*PrivateKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{22}
}

func (m *PrivateKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivateKey.Unmarshal(m, b)
}
func (m *PrivateKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivateKey.Marshal(b, m, deterministic)
}
func (m *PrivateKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivateKey.Merge(m, src)
}
func (m *PrivateKey) XXX_Size() int {
	return xxx_messageInfo_PrivateKey.Size(m)
}
func (m *PrivateKey) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivateKey.DiscardUnknown(m)
}

var xxx_messageInfo_PrivateKey proto.InternalMessageInfo

func (m *PrivateKey) GetPriKey() string {
	if m != nil {
		return m.PriKey
	}
	return ""
}

type PrivKeyAndPassphrase struct {
	PriKey               string   `protobuf:"bytes,1,opt,name=pri_key,json=priKey,proto3" json:"pri_key,omitempty"`
	Passphrase           string   `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrivKeyAndPassphrase) Reset()         { *m = PrivKeyAndPassphrase{} }
func (m *PrivKeyAndPassphrase) String() string { return proto.CompactTextString(m) }
func (*PrivKeyAndPassphrase) ProtoMessage()    {}
func (*PrivKeyAndPassphrase) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{23}
}

func (m *PrivKeyAndPassphrase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrivKeyAndPassphrase.Unmarshal(m, b)
}
func (m *PrivKeyAndPassphrase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrivKeyAndPassphrase.Marshal(b, m, deterministic)
}
func (m *PrivKeyAndPassphrase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrivKeyAndPassphrase.Merge(m, src)
}
func (m *PrivKeyAndPassphrase) XXX_Size() int {
	return xxx_messageInfo_PrivKeyAndPassphrase.Size(m)
}
func (m *PrivKeyAndPassphrase) XXX_DiscardUnknown() {
	xxx_messageInfo_PrivKeyAndPassphrase.DiscardUnknown(m)
}

var xxx_messageInfo_PrivKeyAndPassphrase proto.InternalMessageInfo

func (m *PrivKeyAndPassphrase) GetPriKey() string {
	if m != nil {
		return m.PriKey
	}
	return ""
}

func (m *PrivKeyAndPassphrase) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

func init() {
	proto.RegisterType((*NonParamsRequest)(nil), "rpcpb.NonParamsRequest")
	proto.RegisterType((*AccountsResponse)(nil), "rpcpb.AccountsResponse")
	proto.RegisterType((*PassphraseRequest)(nil), "rpcpb.PassphraseRequest")
	proto.RegisterType((*UpdateAccountRequest)(nil), "rpcpb.UpdateAccountRequest")
	proto.RegisterType((*NewAccountResponse)(nil), "rpcpb.NewAccountResponse")
	proto.RegisterType((*UnlockAccountRequest)(nil), "rpcpb.UnlockAccountRequest")
	proto.RegisterType((*LockAccountRequest)(nil), "rpcpb.LockAccountRequest")
	proto.RegisterType((*SignHashRequest)(nil), "rpcpb.SignHashRequest")
	proto.RegisterType((*VerifyMessageRequest)(nil), "rpcpb.VerifyMessageRequest")
	proto.RegisterType((*SignHashResponse)(nil), "rpcpb.SignHashResponse")
	proto.RegisterType((*SignTransactionPassphraseRequest)(nil), "rpcpb.SignTransactionPassphraseRequest")
	proto.RegisterType((*SignTransactionPassphraseResponse)(nil), "rpcpb.SignTransactionPassphraseResponse")
	proto.RegisterType((*SendTransactionPassphraseRequest)(nil), "rpcpb.SendTransactionPassphraseRequest")
	proto.RegisterType((*GasPriceResponse)(nil), "rpcpb.GasPriceResponse")
	proto.RegisterType((*PprofRequest)(nil), "rpcpb.PprofRequest")
	proto.RegisterType((*PprofResponse)(nil), "rpcpb.PprofResponse")
	proto.RegisterType((*TransactionHash)(nil), "rpcpb.TransactionHash")
	proto.RegisterType((*TransactionRequest)(nil), "rpcpb.TransactionRequest")
	proto.RegisterType((*BoolResponse)(nil), "rpcpb.BoolResponse")
	proto.RegisterType((*Address)(nil), "rpcpb.Address")
	proto.RegisterType((*BalanceResponse)(nil), "rpcpb.BalanceResponse")
	proto.RegisterType((*LoggingInfo)(nil), "rpcpb.LoggingInfo")
	proto.RegisterType((*PrivateKey)(nil), "rpcpb.PrivateKey")
	proto.RegisterType((*PrivKeyAndPassphrase)(nil), "rpcpb.privKeyAndPassphrase")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 1211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0xcf, 0x6e, 0x1b, 0xb7,
	0x13, 0x86, 0x6c, 0xc5, 0xb2, 0xc6, 0x96, 0xed, 0xd0, 0xfa, 0xd9, 0xb2, 0xac, 0xf8, 0xe7, 0xd0,
	0x75, 0x62, 0xf4, 0x60, 0xb5, 0xc9, 0xa1, 0x40, 0x7b, 0xb2, 0x0f, 0x4d, 0x03, 0x3b, 0x89, 0x20,
	0x27, 0x75, 0x4e, 0x55, 0x69, 0x2d, 0xb5, 0x62, 0xb3, 0x22, 0xb7, 0x24, 0x25, 0x43, 0x3d, 0xb4,
	0x40, 0x7b, 0x2e, 0x50, 0xa0, 0x2f, 0xd1, 0x97, 0xe9, 0xa9, 0xaf, 0xd0, 0x07, 0x29, 0x48, 0x91,
	0xbb, 0xab, 0x7f, 0x56, 0x02, 0x14, 0xe8, 0x8d, 0x9c, 0xfd, 0xf8, 0x7d, 0xc3, 0x21, 0x87, 0x33,
	0x0b, 0x45, 0x19, 0xb7, 0x4f, 0x63, 0x29, 0xb4, 0x40, 0xf7, 0x64, 0xdc, 0x8e, 0x6f, 0xaa, 0xb5,
	0x50, 0x88, 0x30, 0xa2, 0x75, 0x12, 0xb3, 0x3a, 0xe1, 0x5c, 0x68, 0xa2, 0x99, 0xe0, 0x6a, 0x04,
	0xc2, 0x08, 0xb6, 0x5e, 0x0a, 0xde, 0x20, 0x92, 0xf4, 0x54, 0x93, 0x7e, 0xdf, 0xa7, 0x4a, 0xe3,
	0x4f, 0x60, 0xeb, 0xac, 0xdd, 0x16, 0x7d, 0xae, 0x55, 0x93, 0xaa, 0x58, 0x70, 0x45, 0x51, 0x0d,
	0x8a, 0x24, 0x08, 0x24, 0x55, 0x8a, 0xaa, 0x4a, 0xee, 0x70, 0xf9, 0xa4, 0xd8, 0x4c, 0x0d, 0xf8,
	0x29, 0xdc, 0x6f, 0x10, 0xa5, 0xe2, 0xae, 0x24, 0x8a, 0x3a, 0x1a, 0x74, 0x00, 0x10, 0x27, 0xc6,
	0x4a, 0xee, 0x30, 0x77, 0x52, 0x6c, 0x66, 0x2c, 0xf8, 0x47, 0x28, 0xbf, 0x89, 0x03, 0xa2, 0xa9,
	0x13, 0xf3, 0xeb, 0x2a, 0x50, 0x70, 0xcc, 0x6e, 0x91, 0x9f, 0xa2, 0x63, 0xd8, 0x10, 0x51, 0xd0,
	0xca, 0xb0, 0x2e, 0x59, 0x40, 0x49, 0x44, 0x41, 0xaa, 0x6f, 0x60, 0x9c, 0xde, 0x66, 0x61, 0xcb,
	0x23, 0x18, 0xa7, 0xb7, 0x29, 0x0c, 0x9f, 0x03, 0x7a, 0x49, 0x6f, 0x13, 0x71, 0xb7, 0xd1, 0xf9,
	0xea, 0x08, 0xf2, 0x3d, 0xda, 0x13, 0x4e, 0xd3, 0x8e, 0x71, 0x04, 0xe5, 0x37, 0x3c, 0x12, 0xed,
	0x77, 0xef, 0xbd, 0x87, 0xf1, 0xa8, 0x2c, 0x4d, 0x46, 0x05, 0x55, 0x61, 0x35, 0xe8, 0x4b, 0x7b,
	0x46, 0xd6, 0xed, 0x7c, 0x33, 0x99, 0xe3, 0x53, 0x40, 0x97, 0x1f, 0xa0, 0x85, 0xaf, 0x61, 0xf3,
	0x8a, 0x85, 0xfc, 0x2b, 0xa2, 0xba, 0x8b, 0x1d, 0xab, 0x40, 0xa1, 0x47, 0x95, 0x22, 0xa1, 0xf7,
	0xca, 0x4f, 0xd1, 0x16, 0x2c, 0x93, 0x28, 0xb4, 0xde, 0x94, 0x9a, 0x66, 0x88, 0xbb, 0x50, 0xfe,
	0x9a, 0x4a, 0xd6, 0x19, 0xbe, 0x18, 0x41, 0x16, 0xb3, 0xd7, 0xa0, 0xa8, 0x58, 0xc8, 0x89, 0xee,
	0x4b, 0xcf, 0x9f, 0x1a, 0xb2, 0xda, 0xcb, 0x63, 0xda, 0xf8, 0x11, 0x6c, 0xa5, 0x5b, 0x70, 0x47,
	0x84, 0x20, 0x1f, 0x10, 0x4d, 0x9c, 0x84, 0x1d, 0xe3, 0x9f, 0xe0, 0xd0, 0xe0, 0x5e, 0x4b, 0xc2,
	0x15, 0x69, 0x9b, 0x68, 0x4d, 0x5f, 0xc8, 0x2f, 0x60, 0x4d, 0xa7, 0xdf, 0xed, 0xf2, 0xb5, 0x27,
	0x7b, 0xa7, 0x36, 0x4d, 0x4e, 0x33, 0x2b, 0x1d, 0xbe, 0x99, 0x45, 0x2f, 0x3a, 0x37, 0xfc, 0x19,
	0x3c, 0xbc, 0xc3, 0x81, 0x19, 0x9e, 0xaf, 0x67, 0x3c, 0xa7, 0x3c, 0xf8, 0xef, 0x3c, 0xaf, 0xc3,
	0xd6, 0x33, 0xa2, 0x1a, 0x92, 0xb5, 0x53, 0x47, 0xf7, 0xa1, 0x18, 0x12, 0xd5, 0x8a, 0x8d, 0xd1,
	0xc5, 0x79, 0x35, 0x74, 0x20, 0xfc, 0x08, 0xd6, 0x1b, 0xb1, 0x14, 0x1d, 0xef, 0xdd, 0x0e, 0xac,
	0x44, 0x4c, 0x69, 0xca, 0x1d, 0xd2, 0xcd, 0xf0, 0x63, 0x28, 0x39, 0x9c, 0x63, 0xdd, 0x81, 0x15,
	0x49, 0x55, 0x3f, 0xd2, 0x16, 0xb8, 0xda, 0x74, 0x33, 0x7c, 0x0c, 0x9b, 0x99, 0x4d, 0x98, 0xb3,
	0x36, 0x91, 0xea, 0x12, 0xd5, 0xf5, 0x67, 0x6c, 0xc6, 0xf8, 0x8f, 0x1c, 0xa0, 0xe9, 0xcd, 0x1a,
	0x68, 0x47, 0x8a, 0x9e, 0x87, 0x9a, 0x31, 0xda, 0x80, 0x25, 0xed, 0x33, 0x75, 0x49, 0x0b, 0x54,
	0x86, 0x7b, 0x03, 0x12, 0xf5, 0xfd, 0xf5, 0x1a, 0x4d, 0x8c, 0x95, 0x0b, 0xde, 0xa6, 0x95, 0xbc,
	0x4d, 0xb4, 0xd1, 0x24, 0x39, 0xa4, 0x7b, 0xe9, 0xf5, 0x32, 0x36, 0x3d, 0x8c, 0x69, 0x65, 0x65,
	0x64, 0x33, 0x63, 0x93, 0xa9, 0xb1, 0x64, 0x42, 0x32, 0x3d, 0xac, 0x14, 0x6c, 0x6e, 0x24, 0x73,
	0x13, 0xa2, 0x73, 0x21, 0xa2, 0x85, 0x3b, 0x3f, 0x82, 0xc2, 0x59, 0x9a, 0x7f, 0x73, 0xd2, 0xb8,
	0x07, 0x9b, 0xe7, 0x24, 0x22, 0x3c, 0x73, 0x3e, 0x15, 0x28, 0xdc, 0x8c, 0x4c, 0x1e, 0xec, 0xa6,
	0xe8, 0xff, 0xb0, 0xd6, 0x91, 0xe2, 0x07, 0xca, 0x5b, 0x9d, 0x3e, 0x0f, 0xfc, 0x71, 0x8f, 0x4c,
	0x5f, 0xf6, 0x79, 0x60, 0x00, 0x71, 0x44, 0x83, 0x90, 0x8e, 0x00, 0xcb, 0xee, 0x3e, 0x58, 0x93,
	0x01, 0xe0, 0x5f, 0x72, 0xb0, 0x76, 0x29, 0xc2, 0x90, 0xf1, 0xf0, 0x39, 0xef, 0x08, 0x73, 0x17,
	0x22, 0x11, 0xb6, 0x22, 0x3a, 0xa0, 0x91, 0xbf, 0x0b, 0x91, 0x08, 0x2f, 0xcd, 0x1c, 0xed, 0x81,
	0x19, 0xb7, 0x62, 0xa2, 0xbb, 0xfe, 0xd9, 0x88, 0x44, 0xd8, 0x20, 0xba, 0x8b, 0x8e, 0xa0, 0x24,
	0x5d, 0xb5, 0x69, 0x69, 0xd6, 0xa3, 0xee, 0x01, 0x59, 0xf7, 0xc6, 0xd7, 0xac, 0x47, 0xd1, 0x2e,
	0x18, 0x7c, 0xcb, 0x64, 0x7e, 0xde, 0x7e, 0x5e, 0x89, 0x44, 0x78, 0x16, 0x52, 0x7c, 0x0c, 0xd0,
	0x90, 0x6c, 0x40, 0x34, 0xbd, 0xa0, 0x43, 0x03, 0x8b, 0x25, 0x6b, 0xbd, 0xa3, 0x43, 0x7f, 0xc7,
	0x62, 0xc9, 0x2e, 0xe8, 0x10, 0xbf, 0x82, 0x72, 0x2c, 0xd9, 0xe0, 0x82, 0x0e, 0xcf, 0x78, 0xb6,
	0x06, 0xcc, 0x5b, 0xb0, 0x28, 0x1b, 0x9e, 0xfc, 0x59, 0x82, 0xf5, 0xb3, 0xa0, 0xc7, 0xf8, 0x15,
	0x95, 0x03, 0xd6, 0xa6, 0xe8, 0x1b, 0x58, 0xbb, 0xd2, 0x44, 0xea, 0x17, 0x8c, 0x33, 0x1e, 0xa2,
	0x8a, 0xcb, 0xba, 0xa9, 0x24, 0xad, 0x6e, 0xbb, 0x2f, 0xd9, 0x83, 0xc7, 0x87, 0x3f, 0xff, 0xf5,
	0xf7, 0xef, 0x4b, 0x55, 0xfc, 0xbf, 0xfa, 0xe0, 0xd3, 0x3a, 0x31, 0xbc, 0x75, 0x95, 0xb2, 0x7d,
	0x9e, 0xfb, 0x18, 0xbd, 0x05, 0xb8, 0xd2, 0x22, 0x76, 0xf4, 0xbb, 0x8e, 0x64, 0xb2, 0x28, 0xcf,
	0x66, 0xaf, 0x59, 0xf6, 0x1d, 0x5c, 0xce, 0xb2, 0x27, 0x5c, 0x6f, 0x61, 0xd5, 0xd7, 0xf1, 0xf9,
	0xbc, 0xfe, 0xc3, 0x64, 0xc5, 0xc7, 0x55, 0xcb, 0x5d, 0x46, 0x28, 0xe5, 0x26, 0x9e, 0xad, 0x0d,
	0x90, 0x96, 0xce, 0x3b, 0x42, 0xe2, 0x9f, 0xa8, 0xe9, 0x3a, 0x3b, 0x2b, 0x30, 0x8e, 0xbe, 0xce,
	0xe9, 0xad, 0x09, 0x4c, 0x07, 0x4a, 0x63, 0xfd, 0x01, 0xda, 0x77, 0x6c, 0xb3, 0xba, 0x86, 0xd9,
	0xf1, 0x39, 0xb2, 0x22, 0x0f, 0x70, 0x65, 0x5a, 0xa4, 0x6f, 0x49, 0x8c, 0x0e, 0x81, 0xd2, 0xf3,
	0x5e, 0x2c, 0xa4, 0x9e, 0xd4, 0x99, 0x75, 0xb1, 0xaa, 0x1b, 0x3e, 0x5e, 0x2e, 0x39, 0xef, 0x90,
	0x60, 0x96, 0xd5, 0x6f, 0x25, 0xdb, 0x26, 0xa4, 0x5b, 0x99, 0xd1, 0x3c, 0x7c, 0xf8, 0x56, 0x2c,
	0x89, 0xd1, 0xf9, 0xd6, 0x64, 0x6e, 0xaa, 0xe2, 0xc3, 0x7f, 0xf9, 0x9e, 0x1a, 0x0f, 0xad, 0xc6,
	0x3e, 0xde, 0x99, 0xd6, 0xf0, 0x0a, 0xdf, 0xc1, 0xe6, 0x44, 0xb5, 0x42, 0xf3, 0xeb, 0x50, 0x75,
	0x67, 0xfa, 0x93, 0x79, 0xdd, 0xf1, 0x47, 0x56, 0xe8, 0x00, 0xef, 0x65, 0xee, 0xed, 0x38, 0xab,
	0xd1, 0xba, 0x86, 0xbc, 0x29, 0xa9, 0xc8, 0xb3, 0x4c, 0xf4, 0x32, 0xc9, 0xd5, 0x9d, 0x6c, 0x10,
	0xf0, 0x81, 0xa5, 0xaf, 0xe0, 0xed, 0x0c, 0x3d, 0x0b, 0x79, 0xdd, 0x54, 0x11, 0x43, 0x4c, 0xa1,
	0x34, 0xd6, 0xbe, 0x24, 0xc7, 0x31, 0xab, 0xa9, 0x99, 0x1d, 0x2a, 0x6c, 0x25, 0x6a, 0x78, 0x37,
	0x95, 0x18, 0x64, 0x17, 0x1b, 0x99, 0x5f, 0x73, 0xf0, 0x60, 0xa2, 0x27, 0xb8, 0x66, 0xba, 0x9b,
	0x79, 0xa5, 0x1e, 0x67, 0x76, 0x70, 0x57, 0x03, 0x50, 0x3d, 0x59, 0x0c, 0x74, 0x8e, 0xed, 0x59,
	0xc7, 0xb6, 0xf1, 0xc6, 0xf8, 0xde, 0x8d, 0x3f, 0xbf, 0x19, 0x7f, 0xc6, 0xc3, 0x3c, 0xcf, 0x9f,
	0x05, 0x0d, 0xc9, 0xdc, 0x83, 0x3d, 0xb5, 0xea, 0x27, 0xf8, 0x28, 0x55, 0xd7, 0xf3, 0xd4, 0x8c,
	0x4b, 0x57, 0xe6, 0xf1, 0x23, 0x52, 0xdb, 0x3e, 0x01, 0xf9, 0x48, 0x67, 0xbb, 0x8b, 0x6a, 0x79,
	0xdc, 0x38, 0xfe, 0x3a, 0xe1, 0xcd, 0x54, 0x28, 0x36, 0x00, 0x43, 0xda, 0x84, 0xbc, 0x79, 0x51,
	0xff, 0x9d, 0xb7, 0xd4, 0x94, 0x01, 0x2a, 0xd1, 0x2b, 0x28, 0xb8, 0x9a, 0x88, 0x50, 0x92, 0x55,
	0x49, 0x8d, 0xac, 0xce, 0xb0, 0x25, 0x84, 0xf7, 0x53, 0xc2, 0x68, 0xf4, 0x79, 0xf4, 0x24, 0xa0,
	0x67, 0x94, 0x53, 0x49, 0x34, 0xcd, 0xd6, 0xb9, 0x79, 0x2e, 0xdf, 0xf7, 0x51, 0x48, 0xb0, 0x3e,
	0x89, 0x50, 0x2d, 0xe5, 0x0f, 0xa7, 0x18, 0x6f, 0x56, 0xec, 0x7f, 0xde, 0xd3, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xd7, 0x1d, 0x4a, 0xd5, 0x19, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminServiceClient interface {
	// start mining
	StartMining(ctx context.Context, in *PassphraseRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	// stop mining
	StopMining(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	// Accounts return account list.
	Accounts(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*AccountsResponse, error)
	// NewAccount create a new account with passphrase
	NewAccount(ctx context.Context, in *PassphraseRequest, opts ...grpc.CallOption) (*NewAccountResponse, error)
	// NewAccount create a new account with passphrase
	UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	// NewAccount create a new account with passphrase
	ImportAccount(ctx context.Context, in *PrivKeyAndPassphrase, opts ...grpc.CallOption) (*Address, error)
	// UnlockAccount unlock account with passphrase
	UnlockAccount(ctx context.Context, in *UnlockAccountRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	// LockAccount lock account
	LockAccount(ctx context.Context, in *LockAccountRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	// Verify, sign, and send the transaction.
	SendTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionHash, error)
	// Sign sign msg
	Sign(ctx context.Context, in *SignHashRequest, opts ...grpc.CallOption) (*SignHashResponse, error)
	// Sign sign msg
	VerifyMessage(ctx context.Context, in *VerifyMessageRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	// Sign sign transaction
	SignTransactionWithPassphrase(ctx context.Context, in *SignTransactionPassphraseRequest, opts ...grpc.CallOption) (*SignTransactionPassphraseResponse, error)
	// SendTransactionWithPassphrase send transaction with passphrase
	SendTransactionWithPassphrase(ctx context.Context, in *SendTransactionPassphraseRequest, opts ...grpc.CallOption) (*TransactionHash, error)
	StartPprof(ctx context.Context, in *PprofRequest, opts ...grpc.CallOption) (*PprofResponse, error)
	//return transaction
	Stop(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	//return Logging Info
	Logging(ctx context.Context, in *LoggingInfo, opts ...grpc.CallOption) (*LoggingInfo, error)
	//Return the key pair
	GeneratePrivateKey(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*PrivateKey, error)
}

type adminServiceClient struct {
	cc *grpc.ClientConn
}

func NewAdminServiceClient(cc *grpc.ClientConn) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) StartMining(ctx context.Context, in *PassphraseRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/StartMining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StopMining(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/StopMining", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Accounts(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*AccountsResponse, error) {
	out := new(AccountsResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/Accounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) NewAccount(ctx context.Context, in *PassphraseRequest, opts ...grpc.CallOption) (*NewAccountResponse, error) {
	out := new(NewAccountResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/NewAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/UpdateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ImportAccount(ctx context.Context, in *PrivKeyAndPassphrase, opts ...grpc.CallOption) (*Address, error) {
	out := new(Address)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/ImportAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UnlockAccount(ctx context.Context, in *UnlockAccountRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/UnlockAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) LockAccount(ctx context.Context, in *LockAccountRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/LockAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SendTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*TransactionHash, error) {
	out := new(TransactionHash)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/SendTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Sign(ctx context.Context, in *SignHashRequest, opts ...grpc.CallOption) (*SignHashResponse, error) {
	out := new(SignHashResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/Sign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) VerifyMessage(ctx context.Context, in *VerifyMessageRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/VerifyMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SignTransactionWithPassphrase(ctx context.Context, in *SignTransactionPassphraseRequest, opts ...grpc.CallOption) (*SignTransactionPassphraseResponse, error) {
	out := new(SignTransactionPassphraseResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/SignTransactionWithPassphrase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) SendTransactionWithPassphrase(ctx context.Context, in *SendTransactionPassphraseRequest, opts ...grpc.CallOption) (*TransactionHash, error) {
	out := new(TransactionHash)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/SendTransactionWithPassphrase", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StartPprof(ctx context.Context, in *PprofRequest, opts ...grpc.CallOption) (*PprofResponse, error) {
	out := new(PprofResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/StartPprof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Stop(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) Logging(ctx context.Context, in *LoggingInfo, opts ...grpc.CallOption) (*LoggingInfo, error) {
	out := new(LoggingInfo)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/Logging", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GeneratePrivateKey(ctx context.Context, in *NonParamsRequest, opts ...grpc.CallOption) (*PrivateKey, error) {
	out := new(PrivateKey)
	err := c.cc.Invoke(ctx, "/rpcpb.AdminService/GeneratePrivateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
type AdminServiceServer interface {
	// start mining
	StartMining(context.Context, *PassphraseRequest) (*BoolResponse, error)
	// stop mining
	StopMining(context.Context, *NonParamsRequest) (*BoolResponse, error)
	// Accounts return account list.
	Accounts(context.Context, *NonParamsRequest) (*AccountsResponse, error)
	// NewAccount create a new account with passphrase
	NewAccount(context.Context, *PassphraseRequest) (*NewAccountResponse, error)
	// NewAccount create a new account with passphrase
	UpdateAccount(context.Context, *UpdateAccountRequest) (*BoolResponse, error)
	// NewAccount create a new account with passphrase
	ImportAccount(context.Context, *PrivKeyAndPassphrase) (*Address, error)
	// UnlockAccount unlock account with passphrase
	UnlockAccount(context.Context, *UnlockAccountRequest) (*BoolResponse, error)
	// LockAccount lock account
	LockAccount(context.Context, *LockAccountRequest) (*BoolResponse, error)
	// Verify, sign, and send the transaction.
	SendTransaction(context.Context, *TransactionRequest) (*TransactionHash, error)
	// Sign sign msg
	Sign(context.Context, *SignHashRequest) (*SignHashResponse, error)
	// Sign sign msg
	VerifyMessage(context.Context, *VerifyMessageRequest) (*BoolResponse, error)
	// Sign sign transaction
	SignTransactionWithPassphrase(context.Context, *SignTransactionPassphraseRequest) (*SignTransactionPassphraseResponse, error)
	// SendTransactionWithPassphrase send transaction with passphrase
	SendTransactionWithPassphrase(context.Context, *SendTransactionPassphraseRequest) (*TransactionHash, error)
	StartPprof(context.Context, *PprofRequest) (*PprofResponse, error)
	//return transaction
	Stop(context.Context, *NonParamsRequest) (*BoolResponse, error)
	//return Logging Info
	Logging(context.Context, *LoggingInfo) (*LoggingInfo, error)
	//Return the key pair
	GeneratePrivateKey(context.Context, *NonParamsRequest) (*PrivateKey, error)
}

// UnimplementedAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (*UnimplementedAdminServiceServer) StartMining(ctx context.Context, req *PassphraseRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMining not implemented")
}
func (*UnimplementedAdminServiceServer) StopMining(ctx context.Context, req *NonParamsRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopMining not implemented")
}
func (*UnimplementedAdminServiceServer) Accounts(ctx context.Context, req *NonParamsRequest) (*AccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Accounts not implemented")
}
func (*UnimplementedAdminServiceServer) NewAccount(ctx context.Context, req *PassphraseRequest) (*NewAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewAccount not implemented")
}
func (*UnimplementedAdminServiceServer) UpdateAccount(ctx context.Context, req *UpdateAccountRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccount not implemented")
}
func (*UnimplementedAdminServiceServer) ImportAccount(ctx context.Context, req *PrivKeyAndPassphrase) (*Address, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportAccount not implemented")
}
func (*UnimplementedAdminServiceServer) UnlockAccount(ctx context.Context, req *UnlockAccountRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockAccount not implemented")
}
func (*UnimplementedAdminServiceServer) LockAccount(ctx context.Context, req *LockAccountRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockAccount not implemented")
}
func (*UnimplementedAdminServiceServer) SendTransaction(ctx context.Context, req *TransactionRequest) (*TransactionHash, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransaction not implemented")
}
func (*UnimplementedAdminServiceServer) Sign(ctx context.Context, req *SignHashRequest) (*SignHashResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (*UnimplementedAdminServiceServer) VerifyMessage(ctx context.Context, req *VerifyMessageRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyMessage not implemented")
}
func (*UnimplementedAdminServiceServer) SignTransactionWithPassphrase(ctx context.Context, req *SignTransactionPassphraseRequest) (*SignTransactionPassphraseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignTransactionWithPassphrase not implemented")
}
func (*UnimplementedAdminServiceServer) SendTransactionWithPassphrase(ctx context.Context, req *SendTransactionPassphraseRequest) (*TransactionHash, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTransactionWithPassphrase not implemented")
}
func (*UnimplementedAdminServiceServer) StartPprof(ctx context.Context, req *PprofRequest) (*PprofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartPprof not implemented")
}
func (*UnimplementedAdminServiceServer) Stop(ctx context.Context, req *NonParamsRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedAdminServiceServer) Logging(ctx context.Context, req *LoggingInfo) (*LoggingInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logging not implemented")
}
func (*UnimplementedAdminServiceServer) GeneratePrivateKey(ctx context.Context, req *NonParamsRequest) (*PrivateKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GeneratePrivateKey not implemented")
}

func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_StartMining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassphraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StartMining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/StartMining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StartMining(ctx, req.(*PassphraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StopMining_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StopMining(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/StopMining",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StopMining(ctx, req.(*NonParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Accounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Accounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/Accounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Accounts(ctx, req.(*NonParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_NewAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PassphraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).NewAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/NewAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).NewAccount(ctx, req.(*PassphraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateAccount(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ImportAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrivKeyAndPassphrase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ImportAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/ImportAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ImportAccount(ctx, req.(*PrivKeyAndPassphrase))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UnlockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UnlockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/UnlockAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UnlockAccount(ctx, req.(*UnlockAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_LockAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).LockAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/LockAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).LockAccount(ctx, req.(*LockAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SendTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SendTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/SendTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SendTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/Sign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Sign(ctx, req.(*SignHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_VerifyMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).VerifyMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/VerifyMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).VerifyMessage(ctx, req.(*VerifyMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SignTransactionWithPassphrase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignTransactionPassphraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SignTransactionWithPassphrase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/SignTransactionWithPassphrase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SignTransactionWithPassphrase(ctx, req.(*SignTransactionPassphraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_SendTransactionWithPassphrase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTransactionPassphraseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).SendTransactionWithPassphrase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/SendTransactionWithPassphrase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).SendTransactionWithPassphrase(ctx, req.(*SendTransactionPassphraseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StartPprof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PprofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StartPprof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/StartPprof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StartPprof(ctx, req.(*PprofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Stop(ctx, req.(*NonParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_Logging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoggingInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).Logging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/Logging",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).Logging(ctx, req.(*LoggingInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GeneratePrivateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GeneratePrivateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpcpb.AdminService/GeneratePrivateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GeneratePrivateKey(ctx, req.(*NonParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartMining",
			Handler:    _AdminService_StartMining_Handler,
		},
		{
			MethodName: "StopMining",
			Handler:    _AdminService_StopMining_Handler,
		},
		{
			MethodName: "Accounts",
			Handler:    _AdminService_Accounts_Handler,
		},
		{
			MethodName: "NewAccount",
			Handler:    _AdminService_NewAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _AdminService_UpdateAccount_Handler,
		},
		{
			MethodName: "ImportAccount",
			Handler:    _AdminService_ImportAccount_Handler,
		},
		{
			MethodName: "UnlockAccount",
			Handler:    _AdminService_UnlockAccount_Handler,
		},
		{
			MethodName: "LockAccount",
			Handler:    _AdminService_LockAccount_Handler,
		},
		{
			MethodName: "SendTransaction",
			Handler:    _AdminService_SendTransaction_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _AdminService_Sign_Handler,
		},
		{
			MethodName: "VerifyMessage",
			Handler:    _AdminService_VerifyMessage_Handler,
		},
		{
			MethodName: "SignTransactionWithPassphrase",
			Handler:    _AdminService_SignTransactionWithPassphrase_Handler,
		},
		{
			MethodName: "SendTransactionWithPassphrase",
			Handler:    _AdminService_SendTransactionWithPassphrase_Handler,
		},
		{
			MethodName: "StartPprof",
			Handler:    _AdminService_StartPprof_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _AdminService_Stop_Handler,
		},
		{
			MethodName: "Logging",
			Handler:    _AdminService_Logging_Handler,
		},
		{
			MethodName: "GeneratePrivateKey",
			Handler:    _AdminService_GeneratePrivateKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
